version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      DB_HOST: 5942e-rw.db.pub.dbaas.postgrespro.ru
      POSTGRES_USER: raspopov_si
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dbproject
    ports:
      - "5458:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raspopov_si -d dbproject"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ../server/migrations:/migrations:z
    command: -path /migrations -database "${MIGRATE_URL}" up
    depends_on:
      db:
        condition: service_healthy
      
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3020:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}

      SMTP_HOST: smtp.gmail.com 
      SMTP_PORT: 587      
      SMTP_USER: stepan41kr@gmail.com
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: RoseBank Security <stepan41kr@gmail.com>

      POSTGRES_DB: dbproject       
      POSTGRES_USER: raspopov_si     
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db 
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backups:/root/backups:z

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "3010:80"